name: diary_app_mobile
description: A Flutter mobile app for the diary application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI components
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  flutter_keyboard_visibility: ^6.0.0
  
  # Date and time
  intl: ^0.20.2
  
  # Rich text editor
  flutter_quill: ^11.4.1
  
  # Icons - temporarily removed due to JVM compatibility issues
  # emoji_picker_flutter: ^1.6.1
  
  # Image picker
  image_picker: ^1.0.4
  
  # File handling
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 